  version: '3.8'

  services:
    mysql_movie_db:
      image: mysql:8.1.0
      restart: "no"
      environment:
        MYSQL_DATABASE: 'movie_db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3308:3306'
      networks:
        - backend
      volumes:
        - ./mysql/data:/var/lib/mysql

  networks:
    backend:
      name: back-network
      driver: bridge

